### ISSUE TITLE
[Bug] Label Text is hard to read in dark mode

### ISSUE THREAD

**Issue by joshmc82** [kayyagari/ballista#2]
When using macOS in dark mode, the label text is barely visible. Switching to light mode corrects this. Unsure of how to make that behave differently in dark mode. Thoughts?
![image](https://github.com/kayyagari/catapult/assets/8876483/17499991-6d06-4c75-9efe-e5660b35adfd)

**Comment by kayyagari** [comment]
This is due to app not handling the dark mode. I am investigating a solution.

**Comment by kayyagari** [comment]
Dark mode is now available (depends on the OS theme settings).
