### ISSUE TITLE
[Bug] Cannot launch mirth in Windows

### ISSUE THREAD

**Issue by tonygermano** [kayyagari/ballista#7]
- After clicking the "open" button the "waiting" thing spins for approximately 40 seconds according to my phone's stopwatch.
- Then there is a popup message in the application that says
>Error: The filename, directory name, or volume label syntax is incorrect. (os error 123)
- I believe this has to do with the hard coded `/tmp/catapult` path.
- I'm guessing there is a cross-platform way in rust to get a temp directory (I'm pretty sure java has this.)

**Comment by jonbartels** [comment]
https://doc.rust-lang.org/std/env/fn.temp_dir.html maybe?

**Comment by tonygermano** [comment]
I think this: https://docs.rs/tempdir/latest/tempdir/
I believe under the hood it uses the standard function that Jon mentioned to locate the defined temp dir, but then provides additional methods for creating uniquely named subdirectories under the tempdir and cleaning them up when finished.

**Comment by kayyagari** [comment]
I used the `std::env::temp_dir()` function instead of adding another dependency. d2b44ae should fix it.

**Comment by jonbartels** [comment]
@tonygermano I think the use of temp_dir vs tempdir would depend on if the data is useful after Catapult shuts down. Logs, stack traces, etc should use temp_dir. True working state files with no analytical value should use tempdir.
